"""
Tests for OvertureQueryEngine.

Uses generated test Parquet data (tests/test_boundaries.parquet).
Run `python tests/generate_test_data.py` first if file doesn't exist.
"""
import pytest
import sys
from pathlib import Path
import pandas as pd

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from query_engine import OvertureQueryEngine


@pytest.fixture
def test_parquet_path():
    """Path to test Parquet file."""
    # Generated by tests/generate_test_data.py
    return str(Path(__file__).parent.parent.parent / "tests" / "test_boundaries.parquet")


@pytest.fixture
def engine(test_parquet_path):
    """Create query engine instance with test data."""
    return OvertureQueryEngine(test_parquet_path)


class TestOvertureQueryEngineBasic:
    """Test basic query engine functionality."""

    def test_engine_initialization(self, test_parquet_path):
        """Test that engine can be initialized."""
        engine = OvertureQueryEngine(test_parquet_path)
        assert engine is not None
        assert engine.parquet_path == test_parquet_path
        assert engine.conn is None  # Connection lazy-loaded

    def test_get_connection(self, engine):
        """Test that connection is created on first access."""
        conn = engine._get_connection()
        assert conn is not None

    def test_parquet_path_validation(self):
        """Test that engine accepts various path formats."""
        # Local path
        engine1 = OvertureQueryEngine("/path/to/file.parquet")
        assert engine1.parquet_path == "/path/to/file.parquet"

        # S3 URL
        engine2 = OvertureQueryEngine("s3://bucket/path/*.parquet")
        assert engine2.parquet_path == "s3://bucket/path/*.parquet"

        # Glob pattern
        engine3 = OvertureQueryEngine("/path/**/*.parquet")
        assert engine3.parquet_path == "/path/**/*.parquet"


class TestOvertureQueryEngineWithData:
    """Test query engine with generated test data.

    Note: Test data is auto-generated by conftest.py if missing or outdated.
    """

    def test_get_countries(self, engine):
        """Test retrieving all countries."""
        countries = engine.get_countries()

        assert isinstance(countries, list)
        assert len(countries) == 3  # US, GB, CA

        # Verify structure
        assert all('name' in c for c in countries)
        assert all('division_id' in c for c in countries)
        assert all('subtype' in c for c in countries)
        assert all('country' in c for c in countries)

        # Verify all are countries
        assert all(c['subtype'] == 'country' for c in countries)

        # Check specific countries exist
        country_names = [c['name'] for c in countries]
        assert 'United States' in country_names
        assert 'United Kingdom' in country_names
        assert 'Canada' in country_names

    def test_get_country_division_us(self, engine):
        """Test retrieving US country division."""
        country_div = engine.get_country_division('US')

        assert country_div is not None
        assert country_div['name'] == 'United States'
        assert 'division_id' in country_div

    def test_get_country_division_gb(self, engine):
        """Test retrieving UK country division."""
        country_div = engine.get_country_division('GB')

        assert country_div is not None
        assert country_div['name'] == 'United Kingdom'

    def test_get_country_division_ca(self, engine):
        """Test retrieving Canada country division."""
        country_div = engine.get_country_division('CA')

        assert country_div is not None
        assert country_div['name'] == 'Canada'

    def test_get_country_division_nonexistent(self, engine):
        """Test retrieving non-existent country."""
        country_div = engine.get_country_division('XX')
        assert country_div is None

    def test_get_child_divisions_for_us(self, engine):
        """Test retrieving child divisions for US."""
        # Get US country division ID
        us = engine.get_country_division('US')
        us_id = us['division_id']

        children = engine.get_child_divisions(us_id)

        assert isinstance(children, pd.DataFrame)
        assert len(children) >= 3  # CA, OR, WA states

        # Verify structure
        assert 'name' in children.columns
        assert 'division_id' in children.columns

        # Check states exist
        child_names = children['name'].tolist()
        assert 'California' in child_names
        assert 'Oregon' in child_names
        assert 'Washington' in child_names

    def test_get_child_divisions_for_california(self, engine):
        """Test retrieving child divisions for California."""
        # Get California division ID from test data
        ca_id = '0858d7e2-aa18-ae63-ffff-e4dc0fb91919'

        children = engine.get_child_divisions(ca_id)

        assert isinstance(children, pd.DataFrame)
        assert len(children) >= 2  # LA County, SF County

        child_names = children['name'].tolist()
        assert 'Los Angeles County' in child_names
        assert 'San Francisco County' in child_names

    def test_get_division_by_id(self, engine):
        """Test retrieving division by ID."""
        # Use known test data ID
        division_id = '0858d7df-4c21-6d95-ffff-aadc92e00b0a'  # US

        division = engine.get_division_by_id(division_id)

        assert division is not None
        assert division['division_id'] == division_id
        assert division['name'] == 'United States'
        assert division['country'] == 'US'

    def test_get_division_by_id_nonexistent(self, engine):
        """Test retrieving non-existent division."""
        division = engine.get_division_by_id('nonexistent-id')
        assert division is None

    def test_search_boundaries(self, engine):
        """Test searching boundaries by name."""
        results = engine.search_boundaries('US', 'California')

        assert isinstance(results, pd.DataFrame)
        assert len(results) >= 1

        # Should find California
        assert any(results['name'] == 'California')

    def test_search_boundaries_partial_match(self, engine):
        """Test searching with partial name match."""
        results = engine.search_boundaries('US', 'Los')

        assert isinstance(results, pd.DataFrame)
        # Should find "Los Angeles County"
        assert any(results['name'].str.contains('Los Angeles'))

    def test_search_boundaries_case_insensitive(self, engine):
        """Test that search is case-insensitive."""
        results_lower = engine.search_boundaries('US', 'california')
        results_upper = engine.search_boundaries('US', 'CALIFORNIA')

        # Both should return same results
        assert len(results_lower) == len(results_upper)
        assert len(results_lower) >= 1

    def test_search_boundaries_no_results(self, engine):
        """Test searching with no matches."""
        results = engine.search_boundaries('US', 'Nonexistent Place')
        assert isinstance(results, pd.DataFrame)
        assert len(results) == 0

    def test_get_geometry(self, engine):
        """Test retrieving geometry for a division."""
        # Note: test_boundaries.parquet doesn't have division_area data
        # So this tests that the method handles missing data gracefully
        division_id = '0858d7e4-1234-5678-ffff-abcd12345678'

        geometry = engine.get_geometry(division_id)

        # Should return None when division_area file doesn't exist
        # (query_engine handles errors gracefully)
        assert geometry is None

    def test_cache_behavior(self, engine):
        """Test that queries are cached (Streamlit @cache_data)."""
        # First call
        countries1 = engine.get_countries()

        # Second call (should use cache)
        countries2 = engine.get_countries()

        # Should return same data
        assert len(countries1) == len(countries2)
        assert countries1 == countries2

    def test_get_descendants_depth_1(self, engine):
        """Test getting descendants at depth 1 (direct children)."""
        # Get US country division
        us = engine.get_country_division('US')
        us_id = us['division_id']

        # Get descendants with max_depth=1
        descendants = engine.get_descendants(us_id, max_depth=1)

        assert isinstance(descendants, pd.DataFrame)
        # Should have at least 3 states (CA, OR, WA)
        assert len(descendants) >= 3

        # All should be depth 1
        assert all(descendants['depth'] == 1)

        # Check for expected states
        state_names = descendants['name'].tolist()
        assert 'California' in state_names
        assert 'Oregon' in state_names
        assert 'Washington' in state_names

    def test_get_descendants_depth_2(self, engine):
        """Test getting descendants at depth 2 (children and grandchildren)."""
        # Get US country division
        us = engine.get_country_division('US')
        us_id = us['division_id']

        # Get descendants with max_depth=2
        descendants = engine.get_descendants(us_id, max_depth=2)

        assert isinstance(descendants, pd.DataFrame)
        # Should have states (depth 1) and counties (depth 2)
        assert len(descendants) >= 5  # 3 states + 2 counties

        # Should have both depth 1 and depth 2
        depths = descendants['depth'].unique()
        assert 1 in depths
        assert 2 in depths

    def test_get_descendants_unlimited_depth(self, engine):
        """Test getting all descendants (no depth limit)."""
        # Get US country division
        us = engine.get_country_division('US')
        us_id = us['division_id']

        # Get all descendants (no limit)
        descendants = engine.get_descendants(us_id, max_depth=None)

        assert isinstance(descendants, pd.DataFrame)
        # Should have all divisions under US
        assert len(descendants) >= 5  # At least 3 states + 2 counties

        # Verify depth column exists
        assert 'depth' in descendants.columns

    def test_get_descendants_no_children(self, engine):
        """Test getting descendants for division with no children."""
        # Use a county which has no children
        division_id = '0858d7e4-1234-5678-ffff-abcd12345678'  # LA County

        descendants = engine.get_descendants(division_id, max_depth=None)

        assert isinstance(descendants, pd.DataFrame)
        # Should be empty (no children)
        assert len(descendants) == 0


class TestQueryEngineErrorHandling:
    """Test error handling in query engine."""

    def test_handle_missing_file(self):
        """Test initialization with non-existent file."""
        engine = OvertureQueryEngine("/nonexistent/path.parquet")
        assert engine.parquet_path == "/nonexistent/path.parquet"

        # Querying should handle error gracefully (returns empty list in actual implementation)
        try:
            countries = engine.get_countries()
            # If implementation catches errors, should return empty list
            assert isinstance(countries, list)
        except Exception:
            # If it raises, that's also acceptable
            pass
